(defun atom? (x) ( not (listp x)))
(defun null? (x) (null x))

(defmacro test (x)
  (write x)
  (write ' ---> )
  (write (eval x))
  (terpri)  )

(test (atom? 's))
(test (atom? '(s)))
(test (atom? nil))
(test (atom? (car '(s t))))
(test (atom? (cdr '(s t))))
(test (null? ()))
(test (null? nil))
(test (null? '(s)))
(test (eq 's 'f))
(test (eq 's 's))
